# Generated by Django 5.0.2 on 2024-02-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя(Ник)', max_length=50)),
                ('mail', models.EmailField(blank=True, help_text='Электронная почта', max_length=254, null=True)),
                ('phone', models.CharField(help_text='Телефон', max_length=20)),
            ],
        ),
    ]
