# Generated by Django 5.0.2 on 2024-02-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(help_text='Дата', max_length=30)),
                ('time', models.CharField(help_text='Время', max_length=30)),
                ('temperature_2m', models.CharField(help_text='Температура на 2м', max_length=20)),
                ('temperature_120m', models.CharField(help_text='Температура на 120м', max_length=20)),
                ('relative_humidity_2m', models.CharField(help_text='Влажность', max_length=20)),
                ('precipitation_probability', models.CharField(help_text='Вероятность осадков', max_length=20)),
                ('visibility', models.CharField(help_text='Видимость', max_length=20)),
                ('wind_speed_10m', models.CharField(help_text='Скорость ветра на 10м', max_length=20)),
                ('wind_speed_120m', models.CharField(help_text='Скорость ветра на 120м', max_length=20)),
                ('wind_gusts_10m', models.CharField(help_text='Порывы ветра на 10м', max_length=20)),
                ('wind_direction_10m', models.CharField(help_text='Направление ветра на 10м', max_length=20)),
                ('wind_direction_120m', models.CharField(help_text='Направление ветра на 120м', max_length=20)),
            ],
        ),
    ]
